# Render deployment configuration
services:
  - type: web
    name: car-dealership
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn dealership_project.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"