# Generated by Django 5.2.6 on 2025-09-14 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealerships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('purchase', models.BooleanField(default=False)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('car_make', models.CharField(blank=True, max_length=100, null=True)),
                ('car_model', models.CharField(blank=True, max_length=100, null=True)),
                ('car_year', models.IntegerField(blank=True, null=True)),
                ('sentiment', models.CharField(default='neutral', max_length=10)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealerships.dealership')),
            ],
        ),
    ]
